"""
YU HOLDINGS AI Company - エージェント定義
"""

AGENTS = [
    # ─── 経営層 ───
    {
        "id": "coo",
        "name": "AI COO",
        "role": "最高執行責任者",
        "icon": "⚙️",
        "tier": "executive",
        "color": "#6366f1",
        "tasks": [
            "全事業データ収集中...",
            "売上達成率を分析中...",
            "危険事業のアラート確認...",
            "今週TOP3アクション策定...",
            "CEOブリーフィング生成中...",
            "優先順位を決定中...",
            "週次実行計画を更新中...",
        ],
        "interval_range": (8, 18),
    },
    {
        "id": "cfo",
        "name": "AI CFO",
        "role": "最高財務責任者",
        "icon": "💰",
        "tier": "executive",
        "color": "#10b981",
        "tasks": [
            "全事業売上データ集計中...",
            "達成率ランキング算出中...",
            "キャッシュフロー予測中...",
            "投資優先順位を分析中...",
            "財務リスクアラート確認...",
            "月次財務レポート生成中...",
        ],
        "interval_range": (10, 20),
    },
    {
        "id": "cmo",
        "name": "AI CMO",
        "role": "最高マーケティング責任者",
        "icon": "📣",
        "tier": "executive",
        "color": "#f59e0b",
        "tasks": [
            "SNS媒体稼働状況を確認中...",
            "Instagram/Threads投稿分析...",
            "コンテンツ戦略を策定中...",
            "次の優先プラットフォーム選定...",
            "マーケティングKPI確認中...",
            "180日分コンテンツ進捗確認...",
        ],
        "interval_range": (12, 22),
    },
    {
        "id": "cto",
        "name": "AI CTO",
        "role": "最高技術責任者",
        "icon": "🛡️",
        "tier": "executive",
        "color": "#ef4444",
        "tasks": [
            "Cloud Run ヘルスチェック中...",
            "スケジューラー稼働確認...",
            "エラーログ監視中...",
            "API応答速度を計測中...",
            "デプロイキュー確認中...",
            "インフラコスト最適化確認...",
        ],
        "interval_range": (5, 12),
    },

    # ─── コンテンツエンジン（5事業） ───
    {
        "id": "content_beauty",
        "name": "Beauty コンテンツAI",
        "role": "Tree Beauty SNS自動投稿",
        "icon": "💆",
        "tier": "content",
        "color": "#ec4899",
        "tasks": [
            "脱毛・美容メニューコンテンツ生成中...",
            "Instagram用ハッシュタグ最適化...",
            "Threads投稿文を生成中...",
            "GBP投稿を生成中...",
            "LINE配信テキスト作成中...",
            "画像マネージャーに画像リクエスト送信...",
            "HPB向けブログ下書き生成中...",
        ],
        "interval_range": (15, 30),
    },
    {
        "id": "content_catering",
        "name": "Catering コンテンツAI",
        "role": "Trees Catering SNS自動投稿",
        "icon": "🍱",
        "tier": "content",
        "color": "#8b5cf6",
        "tasks": [
            "ケータリングメニュー投稿生成中...",
            "法人向けオードブル訴求文作成...",
            "会議弁当シーズナルコンテンツ生成...",
            "Threads用ショート投稿作成中...",
            "LINE法人顧客向けメッセージ作成...",
            "画像ライブラリから最適画像選定中...",
        ],
        "interval_range": (18, 35),
    },
    {
        "id": "content_tachinomiya",
        "name": "TACHINOMIYA コンテンツAI",
        "role": "立飲み屋 SNS自動投稿",
        "icon": "🍺",
        "tier": "content",
        "color": "#06b6d4",
        "tasks": [
            "フード・ドリンクメニュー投稿生成...",
            "UberEats/出前館向け訴求文作成...",
            "サーターアンダギー特集投稿生成...",
            "BAR営業時間告知コンテンツ生成...",
            "Instagram リール用テキスト生成...",
            "Threads用おすすめメニュー投稿作成...",
        ],
        "interval_range": (16, 32),
    },
    {
        "id": "content_hinabe",
        "name": "琉球火鍋 コンテンツAI",
        "role": "ryukyu_hinabe SNS自動投稿",
        "icon": "🔥",
        "tier": "content",
        "color": "#f97316",
        "tasks": [
            "火鍋スープ・食材投稿生成中...",
            "宴会プラン訴求コンテンツ作成...",
            "Instagram用火鍋写真キャプション生成...",
            "Threads向け沖縄食材アピール投稿...",
            "LINE宴会告知メッセージ生成中...",
            "GBP口コミ返信文を生成中...",
        ],
        "interval_range": (20, 38),
    },
    {
        "id": "content_pasta",
        "name": "パスタパスタ コンテンツAI",
        "role": "パスタパスタ SNS自動投稿",
        "icon": "🍝",
        "tier": "content",
        "color": "#84cc16",
        "tasks": [
            "本日のランチメニュー投稿生成...",
            "パスタ新メニュー紹介文を作成...",
            "Instagram用フード写真キャプション生成...",
            "Threads向けディナー訴求投稿作成...",
            "LINE顧客向けクーポン告知生成...",
            "HPBレストランページ更新文作成...",
        ],
        "interval_range": (18, 34),
    },

    # ─── オペレーションエージェント ───
    {
        "id": "task_commander",
        "name": "タスク指令AI",
        "role": "Daily Action Commander",
        "icon": "📋",
        "tier": "ops",
        "color": "#64748b",
        "tasks": [
            "各事業スタッフのタスク生成中...",
            "LINE経由でタスク配信中...",
            "タスク完了確認メッセージ処理中...",
            "未完了タスクのリマインド送信中...",
            "スタッフ別進捗率を集計中...",
            "オーナーレポート生成中...",
        ],
        "interval_range": (10, 20),
    },
    {
        "id": "image_manager",
        "name": "画像マネージャーAI",
        "role": "Image Manager & GCS",
        "icon": "🖼️",
        "tier": "ops",
        "color": "#0ea5e9",
        "tasks": [
            "Driveから実写画像をスキャン中...",
            "GPT-4o-miniで最適画像を選定中...",
            "選定スコア・使用頻度を算出中...",
            "GCSへ画像をアップロード中...",
            "画像ライブラリのINDEXを更新中...",
            "重複使用防止チェック実行中...",
            "AI画像生成をフォールバック中...",
        ],
        "interval_range": (8, 16),
    },
    {
        "id": "threads_bot",
        "name": "Threadsリプライ AI",
        "role": "Threads Reply Bot",
        "icon": "💬",
        "tier": "ops",
        "color": "#a855f7",
        "tasks": [
            "Threadsのキーワードモニタリング中...",
            "リード候補ユーザーを検出中...",
            "返信文をGPT-4o-miniで生成中...",
            "リプライを投稿中...",
            "エンゲージメント率を計測中...",
            "スパムフィルタリング実行中...",
        ],
        "interval_range": (6, 14),
    },
    {
        "id": "weekly_reporter",
        "name": "週次レポートAI",
        "role": "Weekly Report Generator",
        "icon": "📊",
        "tier": "ops",
        "color": "#14b8a6",
        "tasks": [
            "全事業週次データを集計中...",
            "前週比較分析を生成中...",
            "KPIサマリーを作成中...",
            "Googleスプレッドシートを更新中...",
            "LINE週次レポート送信中...",
            "次週目標を算出中...",
        ],
        "interval_range": (25, 45),
    },
    {
        "id": "blog_generator",
        "name": "ブログ画像AI",
        "role": "Blog Image Generator",
        "icon": "✍️",
        "tier": "ops",
        "color": "#f43f5e",
        "tasks": [
            "ブログ記事テーマを分析中...",
            "DALL-E 3でヘッダー画像生成中...",
            "画像スタイルをビジネスに最適化中...",
            "GCSにブログ画像をアップロード中...",
            "HPBブログとの連携確認中...",
        ],
        "interval_range": (20, 40),
    },
]
